### ISSUE TITLE
Sketch generation fails

### ISSUE THREAD

**Issue by nntae** [utopia-group/regel#13]
Here's a log showing what I get when I try to run the sketch generation for the deepregex dataset, just to test it out.

````
regel@47ab95e094c8:/app$ python3 parse_benchmarks.py --benchmark deepregex
Namespace(beam=200, dataset='deepregex', grammar='turk', infile='dataset/deepregex.raw.txt', max_iter=5, model='pretrained_models/pretrained_turk', outfile='dataset/deepregex.ready.txt', target=-1, topk=25)
sh ./py_scripts/test.sh deepregex "pretrained_models/pretrained_turk" 200 turk
Buildfile: /app/sempre/build.xml

init:
     [exec] Wrote modules with 356 files to module-classes.txt: cache core corenlp cprune freebase geo880 interactive overnight sketch src tables

core:
     [echo] Compiling semparse: core
    [javac] Compiling 135 source files to /app/sempre/classes

BUILD FAILED
/app/sempre/build.xml:36: /app/sempre/lib does not exist.

Total time: 1 second
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/sempre/Master
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.sempre.Master
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
Traceback (most recent call last):
  File "py_scripts/test.py", line 41, in <module>
    main()
  File "py_scripts/test.py", line 38, in main
    test(args)
  File "py_scripts/test.py", line 30, in test
    make_sketch_file(pred_file, output_dir, args.dataset, args.topk)
  File "/app/sempre/py_scripts/postprocess.py", line 201, in make_sketch_file
    with open(pred_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: './regex/data/deepregex/200-pred-test.txt'
cp: cannot stat 'sempre/outputs/deepregex/*': No such file or directory
```

I get a similar error when testing with a custom handmade benchmark. Can you give some indications on how to fix this?

**Comment by thelyad** [comment]
It seems you don't have the sempre/lib folder. Have you first run the ./pull-dependencies script under the sempre folder?

**Comment by nntae** [comment]
> It seems you don't have the sempre/lib folder. Have you first run the ./pull-dependencies script under the sempre folder?

Thank you, that was the issue.

Just one more thing so I can understand the implementation better, can the program perform sketch completion without specifying the ground truth in the benchmark?

**Comment by thelyad** [comment]
The synthesizer doesn't require the ground truth to run. However, you might need to specify the ground truth in the benchmark file in order for the entire script to work (maybe not). I would suggest trying not to include ground truth in the benchmark file and run the script. If there is exception, just fill the ground truth part of the benchmark file with some default regex and that should work.
